### ISSUE TITLE
output results

### ISSUE THREAD

**Issue by emanmaali** [vicTorKd/HorusEye#1]
Hi, 

I am trying to run your code on different datasets; however, the results across all of them are TPR and FPR zero all the time 0. What might the problem be? Here are my arguments when running the code; also, I have attached an example of the results: 

    KITSUNE = False
    OPEN_SOURCE =False
    TRAIN = False
    TEST_ROBUST=False
    TEST = True
    Use_filter = False
    Per_Attack=False
    Test_Throughput=False
    PORT = False
    TWO_D = False
    BATCH_SIZE = 256
    TEST_BATCH_SIZE =60000  # for int8 trt model
    INPUTSIZE = 105
    INT8 = False  # using int8 model after quntization

![Screenshot 2024-07-30 at 18 16 30](https://github.com/user-attachments/assets/67d12a01-6ae6-4975-91a5-fe386390106b)

**Comment by victorkdwu** [comment]
Hi Eman,

Thank you for reaching out and providing your results. After reviewing the attachment, I noticed that the data shape you used (n,1,21) does not match the expected input (n,5,21) for the model.

The dataset needs to go through the feature extraction process which is described in README before it can be fed into the model. Additionally, to be consistent with the workflow in the paper, the values of PORT and TWO_D should be set to True.

Please check the data preprocessing steps and ensure that the data shape is correct. Also, if you intend to use a different dataset, please consider the need for retraining the model accordingly.

Best regards.

**Comment by emanmaali** [comment]
Hi, 
Thanks for your reply, 

For feature extraction, yes, I've managed to extract the features. However, the issue is the same! There is an issue now with shape mismatching. All this happens when using pcap files or any new dataset (pcap files), but the code works smoothly using the extracted features you shared over Google Drive. 

Thanks again,

**Comment by victorkdwu** [comment]
Hi,

Have you modified the parameters related to the model? Such as input_size or network layer structure. Because based on the input data shape (n,1,21) provided in the first image, the program should not execute smoothly. 

My suggestion is to re-clone the repository code and follow the process for your dataset, make sure you remove the argparse related code and set the hyperparameters as below:

```
KITSUNE = False
OPEN_SOURCE =False
TRAIN = False
TEST_ROBUST=False
TEST = True
Use_filter = False
Per_Attack=False
Test_Throughput=False
PORT = True
TWO_D = True
BATCH_SIZE = 256
TEST_BATCH_SIZE =60000  # for int8 trt model
INPUTSIZE = 105
INT8 = False  # using int8 model after quntization
```
